# Generated by Django 5.2.3 on 2025-06-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('studio', 'Studio')], max_length=20)),
                ('listing_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('sold', 'Sold')], max_length=10)),
                ('location', models.CharField(choices=[('downtown', 'Downtown'), ('suburbs', 'Suburbs'), ('countryside', 'Countryside'), ('beachfront', 'Beachfront')], max_length=20)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('square_footage', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
    ]
